# Deploy the site to GH Pages on a push to the 'main' branch

name: Deploy GH Pages

on:
  push:
    branches:
    - 'main'

permissions:
  contents: write

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE: 16

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run export
        env:
          SITE_URL: https://2022.global-climatescope.org/
          MAILCHIMP_ADDRESS: ${{ secrets.MAILCHIMP_ADDRESS }}
          MAPBOX_TOKEN: ${{ secrets.MB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
